#多环境配置
spring:
  profiles:
    active: dev
  mvc:
    format:
      date: ddMMyyyy
  thymeleaf:
    cache: false
    mode: HTML
#可查看那些自动配置类生效
debug: true
---
#生产环境配置
server:
  port:  8180
spring:
  config:
    activate:
      on-profile: prod1
---
#开发环境配置
server:
  port:  8181
spring:
  config:
    activate:
      on-profile: dev1
---
#测试环境配置
server:
  port:  8182
spring:
  config:
    activate:
      on-profile: test1