#spring配置
spring:
  profiles:
    active: dev
  mvc:
    format:
      date: ddMMyyyy
  thymeleaf:
    #关闭模板引擎缓存
    cache: false
  messages:
    basename: i18n.signin
  #可以直接使用H5框架
#    mode: HTML
#server:
#  servlet:
#    context-path: /deng
#可查看那些自动配置类生效
debug: true
#多环境配置
---
#生产环境配置
server:
  port:  8180
spring:
  config:
    activate:
      on-profile: prod1
---
#开发环境配置
server:
  port:  8181
spring:
  config:
    activate:
      on-profile: dev1
---
#测试环境配置
server:
  port:  8182
spring:
  config:
    activate:
      on-profile: test1